---
- name: create static inventory 
  ansible.controller.inventory:
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    validate_certs: no

    name: "{{ inventory_name }}"
    description: "{{ inventory_description }}"
    organization: "{{ inventory_organization }}"
    state: present

  register: inventory_create
  delegate_to: localhost
  when:
    - not remove | default ('false') | bool

- name: add hosts to static inventory 
  ansible.controller.host:
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    validate_certs: no

    inventory: "{{ inventory_name }}"
    
    name: "{{ inner_item.name }}"
    description: "{{ inner_item.description | default(omit) }}"
    enabled: true
    state: present
    variables:
        ansible_host: "{{ inner_item.host_ip | default (omit)  }}"
        ansible_connection: "{{ inner_item.ansible_connection | default (omit) }}"
        ansible_python_interpreter: "{{ inner_item.ansible_python_interpreter | default (omit) }}"

  register: inventory_hosts_create
  delegate_to: localhost
  when:
    - not remove | default ('false') | bool
  loop: "{{ inventory_hosts }}"
  loop_control:
    loop_var: inner_item

- name: remove static inventory
  ansible.controller.inventory:
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    validate_certs: no

    name: "{{ inventory_name }}"
    state: absent
  register: inventory_create
  delegate_to: localhost
  when:
    - remove | default ('false') | bool


- name: Debug inventory create / inventory remove
  debug:
     msg:  |
      {{ inventory_create }}
  when:
    - debug | default ('false') | bool

- name: Debug inventory hosts create / inventory remove
  debug:
     msg:  |
      {{ inventory_hosts_create }}
  when:
    - debug | default ('false') | bool
    - not remove | default ('false') | bool
