---
- name: create job template
  ansible.controller.job_template:
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    validate_certs: no

    name: "{{ jobtemplate_name }}"
    description: "{{ jobtemplate_description | default(omit) }}"
    organization: "{{ jobtemplate_organization | default(omit) }}"
    state: present
    inventory: "{{ jobtemplate_inventory }}"
    project:   "{{ jobtemplate_project }}"
    playbook:  "{{ jobtemplate_playbook }}"
    credentials: "{{ jobtemplate_credentials | default(omit) }}"
    become_enabled: "{{ jobtemplate_become | default(false, true) }}"
    execution_environment: "{{ jobtemplate_ee | default(omit) }}"
    extra_vars: "{{ jobtemplate_extravars | default(omit) }}"
    verbosity:  "{{ jobtemplate_verbosity | default(0, true) }}" 
  register: jobtemplate_create
  delegate_to: localhost
  when:
    - not remove | default ('false') | bool

- name: remove job template
  ansible.controller.job_template:
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    validate_certs: no

    name: "{{ jobtemplate_name }}"
    state: absent
  register: jobtemplate_create
  delegate_to: localhost
  when:
    - remove | default ('false') | bool


- name: Debug jobtemplate create / jobtemplate remove
  debug:
     msg:  |
      {{ jobtemplate_create }}
  when:
    - debug | default ('false') | bool
