---
- name: create ee
  ansible.controller.execution_environment:
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    validate_certs: no

    name: "{{ ee_name }}"
    description: "{{ ee_description | default(omit) }}"
    organization: "{{ ee_organization | default(omit) }}"
    state: present
    image: "{{ ee_image }}"
    credential: "{{ ee_credential | default(omit) }}"
    pull: "{{ ee_pull | default('missing', true) }}"

  delegate_to: localhost
  when:
    - not remove | default ('false') | bool

- name: remove ee
  ansible.controller.execution_environment:
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    validate_certs: no

    name: "{{ ee_name }}"
    image: "{{ ee_image }}"
    #organization: "{{ ee_organization | default(omit) }}"
    state: absent
  delegate_to: localhost
  when:
    - remove | default ('false') | bool
