---
- name: setup prerequisites
  import_tasks: prereq.yml

- name: secure system
  import_tasks: security.yml

- name: setup time service
  import_tasks: setup-chrony.yml

- name: setup named server
  import_tasks: setup-named.yml
  when: bastion_named_enable | bool

- name: setup dhcp server
  import_tasks: setup-dhcpd.yml
  when: bastion_dhcpd_enable | bool

- name: setup http server 
  import_tasks: setup-httpd.yml
  when: bastion_httpd_enable | bool

- name: setup iso management 
  import_tasks: setup-isomgt.yml
  when: bastion_httpd_enable | bool

- name: copy esxi iso to batsion 
  import_tasks: copy-vmwareiso.yml
  when: bastion_httpd_enable | bool

- name: setup nfs server 
  import_tasks: setup-nfsd.yml
  when: bastion_nfsd_enable | bool

- name: add python libs for oneview collection to work
  import_tasks: prep4ov.yml
