---
- name: install httpd
  ansible.builtin.yum:
    name: 
      - httpd.x86_64
      - httpd-tools.x86_64
    state: present

# - name: configure httpd

- name: permit traffic in default zone for http service
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop:
    - http
    - https

- name: start httpd
  ansible.builtin.systemd:
    name: httpd
    state: started
    enabled: true
