---
- name: install chrony
  ansible.builtin.yum:
    name: chrony
    state: present

# - name: configure chronyd
# default configuration good enough

- name: start chronyd
  ansible.builtin.systemd:
    name: chronyd
    state: started
    enabled: true
