---
## Prepare bastion host
## run this best from cmd-line like this
##   ansible-playbook -i invetory/hosts --ask-pass prep_bastion_host.yml
##   this will ask for root password of bastion host


- name: Install packages needed
  yum:
    name: 
      - httpd
      - genisoimage
      - wget
    state: latest

- name: start httpd
  service:
    name: httpd
    state: started
    enabled: true

- name: assure destination directory to be in place
  file: 
    path: "{{ item }}"
    state: directory
    modification_time: preserve
    access_time: preserve
  become: true
  loop:
    - "{{ bastion_iso_dir }}"
    - "{{ bastion_firmware_dir }}"

- name: permit traffic in default zone for http service
  ansible.posix.firewalld:
    service: http
    permanent: true
    immediate: true
    state: enabled

- name: Add Ansible user 'ansible', include to group wheel
  user:
    name: ansible
    groups: wheel
    password: "{{ bastion_ansible_password }}"
    append: true
    state: present

- name: Change to passwordless sudo 
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
