---
- name: install chrony
  ansible.builtin.yum:
    name: chrony
    state: present

- name: configure chronyd
  ansible.builtin.lineinfile:
    path: /etc/chrony.conf
    line: "allow 10.6.0.0/16"
    insertbefore: "^allow"
    firstmatch: true
 

- name: start chronyd
  ansible.builtin.systemd:
    name: chronyd
    state: started
    enabled: true

- name: permit traffic in default zone for ntp service
  ansible.posix.firewalld:
    service: ntp
    permanent: true
    immediate: true
    state: enabled
