---
- name: Switch Server off
  hpe.oneview.oneview_server_hardware:
    hostname: "{{ oneview_host }}"
    username: "{{ oneview_username }}"
    password: "{{ oneview_password }}"
    auth_login_domain: "{{ oneview_domain }}"
    api_version: "{{ oneview_apiversion }}"
    state: power_state_set
    data:
      name : "{{ inventory_hostname }}.hpintelco.org"
      force : false
      powerStateData:
        powerState: "Off"
        powerControl: "MomentaryPress"
  delegate_to: localhost
  ignore_errors: true

- name: Wait till final power state OFF is reached
  hpe.oneview.oneview_server_hardware_facts:
    hostname: "{{ oneview_host }}"
    username: "{{ oneview_username }}"
    password: "{{ oneview_password }}"
    auth_login_domain: "{{ oneview_domain }}"
    api_version: "{{ oneview_apiversion }}"
    name: "{{ inventory_hostname }}.hpintelco.org"
  delegate_to: localhost
  delay: 10
  retries: 30
  until: 
    - server_hardwares.powerState is defined 
    - server_hardwares.powerState == "On"

- name: Gather facts about a Server Hardware by name
  hpe.oneview.oneview_server_hardware_facts:
    hostname: "{{ oneview_host }}"
    username: "{{ oneview_username }}"
    password: "{{ oneview_password }}"
    auth_login_domain: "{{ oneview_domain }}"
    api_version: "{{ oneview_apiversion }}"
    name : "{{ inventory_hostname }}.hpintelco.org"
  delegate_to: localhost

- debug: var=server_hardwares

- name: Remove a server profile 
  hpe.oneview.oneview_server_profile:
    hostname: "{{ oneview_host }}"
    username: "{{ oneview_username }}"
    password: "{{ oneview_password }}"
    auth_login_domain: "{{ oneview_domain }}"
    api_version: "{{ oneview_apiversion }}"

    state: absent
    data:
      "{{ lookup('ansible.builtin.template', 'server_profile_template.j2') | from_yaml }}"
    params:
      force: true
  delegate_to: localhost
  register: result

- name: Remove a Server Hardware from Oneview
  hpe.oneview.oneview_server_hardware:
    hostname: "{{ oneview_host }}"
    username: "{{ oneview_username }}"
    password: "{{ oneview_password }}"
    auth_login_domain: "{{ oneview_domain }}"
    api_version: "{{ oneview_apiversion }}"
    state: absent
    data:
      name : "{{ inventory_hostname }}.hpintelco.org"
  delegate_to: localhost
  ignore_errors: true
