---
- name: Wait for ESXi to be ready
  ansible.builtin.wait_for:
    port: "{{ inner_item }}"
    host: "{{ esxi_hostname }}"
    # all values in seconds
    delay: 5            # wait 5 sec before 1st try
    connect_timeout: 10   # wait 10 sec with each try
    sleep: 20             # wait 20 sec before trying agin
    timeout: 1500         # wait 30 min alltogether before failing
    msg: "ESXi {{ esxi_hostname }} not ready yet"
  delegate_to: localhost
  loop:
    - '902'
    - '80'
    - '443'
  loop_control:
    loop_var: inner_item
  # see: https://kb.vmware.com/s/article/2039095 for needed ports

- name: Wait for ESXi to be ready - twice due to reboot of ESXI
  ansible.builtin.wait_for:
    port: "{{ inner_item }}"
    host: "{{ esxi_hostname }}"
    # all values in seconds
    delay: 5             # wait 5 sec before 1st try
    connect_timeout: 10   # wait 10 sec with each try
    sleep: 20             # wait 20 sec before trying agin
    timeout: 600          # wait 10 min alltogether before failing
    msg: "ESXi {{ esxi_hostname }} not ready after second boot yet"
  delegate_to: localhost
  loop:
    - '902'
    - '80'
    - '443'
  loop_control:
    loop_var: inner_item

- name: Connect the host(s)
  community.vmware.vmware_host:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"

    esxi_hostname: "{{ esxi_hostname  }}"
    esxi_username: "{{ esxi_username }}"
    esxi_password: "{{ esxi_password }}"
    fetch_ssl_thumbprint: true
    datacenter_name: "{{ vcenter_datacentername }}"
    cluster_name: "{{ vcenter_clustername }}"
    # folder: "/{{ vcenter_datacentername }}/host/hosts"
      ## folder: "host/hosts"
  delegate_to: localhost
