---
- name: Add esxi hosts to vcenter
  ansible.builtin.include_tasks:
    file: add-esxi-to-vcenter.yml
  when:
    - not remove | default ('false') | bool

- name: Remove esxi hosts from vcenter
  ansible.builtin.include_tasks: 
    file: remove-esxi-from-vcenter.yml
  when:
    - remove | default ('false') | bool

