---
- name: Disconnect the host(s)
  community.vmware.vmware_host:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"

    esxi_hostname: "{{ esxi_hostname  }}"
    esxi_username: "{{ esxi_username }}"
    esxi_password: "{{ esxi_password }}"
    fetch_ssl_thumbprint: true
    datacenter_name: "bcl"
    folder: "/{{ vcenter_datacentername }}/host/hosts"
      ## folder: "host/hosts"
    state: absent
  delegate_to: localhost
