---
- name: Build a list of all the folders
  vmware.vmware_rest.vcenter_folder_info:
    vcenter_hostname: "{{ vcenter_hostname }}"
    vcenter_username: "{{ vcenter_username }}"
    vcenter_password: "{{ vcenter_password }}"
    vcenter_validate_certs: "{{ vcenter_validate_certs }}"
  register: my_folders
  delegate_to: localhost
  when:
    - debug | default ('false') | bool

- name: print folders found
  debug:
    var: my_folders
  when:
    - debug | default ('false') | bool

- name: Assure to have a Datacenter
  vmware.vmware_rest.vcenter_datacenter:
    vcenter_hostname: "{{ vcenter_hostname }}"
    vcenter_username: "{{ vcenter_username }}"
    vcenter_password: "{{ vcenter_password }}"
    vcenter_validate_certs: "{{ vcenter_validate_certs }}"

    state: present
    name: '{{ vcenter_datacentername }}'
    folder: 'group-d1'
  delegate_to: localhost

- name: Create folders in our datacenter
  community.vmware.vcenter_folder:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter_name: '{{ vcenter_datacentername }}'
    folder_name: "{{ item.name }}"
    folder_type: "{{ item.type }}"
    state: present
  delegate_to: localhost
  loop:
     - name: vms
       type: vm
     - name: hosts
       type: host
     - name: networks
       type: network

- name: Provide information about vCenter folders
  community.vmware.vmware_folder_info:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: '{{ vcenter_datacentername }}'
  delegate_to: localhost
  register: vcenter_folder_info
  when:
    - debug | default ('false') | bool

- name: print community info about folders
  debug:
    var: vcenter_folder_info
  when:
    - debug | default ('false') | bool
