---
- name: Remove port group
  community.vmware.vmware_dvs_portgroup:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    switch_name: "{{ vcenter_vswitchname }}"
    portgroup_name: "{{ vcenter_portgroupname }}"
    vlan_id: "{{ vcenter_vlanid }}"
    state: absent
  delegate_to: localhost
  register: vcenter_vswitch_info

- name: Remove distributed vSwitch
  community.vmware.vmware_dvswitch:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: "{{ vcenter_datacentername }}"
    switch_name: "{{ vcenter_vswitchname }}"
    state: absent
  delegate_to: localhost
  register: vcenter_vswitch_info

- name: Remove Cluster
  community.vmware.vmware_cluster:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: "{{ vcenter_datacentername }}"
    cluster_name: "{{ vcenter_clustername }}"
    state: absent
  delegate_to: localhost

- name: Build a list of all the folders
  vmware.vmware_rest.vcenter_folder_info:
    vcenter_hostname: "{{ vcenter_hostname }}"
    vcenter_username: "{{ vcenter_username }}"
    vcenter_password: "{{ vcenter_password }}"
    vcenter_validate_certs: "{{ vcenter_validate_certs }}"
  register: my_folders
  delegate_to: localhost
  when:
    - debug | default ('false') | bool

- name: print folders found
  debug:
    var: my_folders
  when:
    - debug | default ('false') | bool

- name: Remove folders from datacenter
  community.vmware.vcenter_folder:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter_name: '{{ vcenter_datacentername }}'
    folder_name: "{{ item.name }}"
    folder_type: "{{ item.type }}"
    state: absent
  delegate_to: localhost
  loop:
     - name: vms
       type: vm
     - name: hosts
       type: host
     - name: networks
       type: network

- name: Remove our Datacenter
  community.vmware.vmware_datacenter:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    state: absent
    datacenter_name: '{{ vcenter_datacentername }}'
  delegate_to: localhost
